ktor:
  application:
    modules:
      - com.retheviper.bbs.ServerKt.module
  deployment:
    port: 8080
jwt:
  secret: "secret"
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
  issuer: "ktor sample app"
