ktor {
  application {
    modules = [ com.retheviper.chat.ApplicationKt.module ]
  }
  deployment {
    port = 8080
  }
}

messaging {
  frontend {
    devDir = ${?CHAT_FRONTEND_DEV_DIR}
  }

  database {
    jdbcUrl = ${?CHAT_JDBC_URL}
    jdbcUrl = "jdbc:postgresql://localhost:5432/messaging_app"

    r2dbcUrl = ${?CHAT_R2DBC_URL}
    r2dbcUrl = "r2dbc:postgresql://localhost:5432/messaging_app"

    username = ${?CHAT_DB_USER}
    username = "postgres"

    password = ${?CHAT_DB_PASSWORD}
    password = "postgres"
  }

  bootstrap {
    sampleDataEnabled = true
  }
}
