package com.retheviper.chat.app

internal object AppDefaults {
    const val appTitle = "Chat"
    const val initialStatus = "Choose a workspace or create one."
    const val workspaceSlug = "acme"
    const val workspaceName = "Acme Product"
    const val ownerUserId = "alice"
    const val ownerDisplayName = "Alice"
    const val memberUserId = "bob"
    const val memberDisplayName = "Bob"
    const val channelSlug = "design"
    const val channelName = "design"
    const val channelTopic = "Work in progress and design reviews"
    const val imageName = "Image"
    const val imageFallbackFileName = "image"
}

internal object AppLabels {
    const val chatWorkspace = "Chat Workspace"
    const val join = "Join"
    const val create = "Create"
    const val open = "Open"
    const val back = "Back"
    const val continueLabel = "Continue"
    const val createWorkspace = "Create workspace"
    const val notifications = "Notifications"
    const val channels = "Channels"
    const val workspace = "Workspace"
    const val noMember = "No member"
    const val edit = "Edit"
    const val chooseChannel = "Choose a channel"
    const val selectChannelBody = "Select a channel to start chatting."
    const val openChannel = "Open a channel"
    const val openChannelBody = "Pick #general or another channel from the sidebar."
    const val readMore = "Read more"
    const val loading = "Loading..."
    const val createChannel = "Create a channel"
    const val updateProfile = "Update profile"
    const val slug = "Slug"
    const val name = "Name"
    const val topic = "Topic"
    const val cancel = "Cancel"
    const val save = "Save"
    const val displayName = "Display name"
    const val userId = "User ID"
    const val thread = "Thread"
    const val close = "Close"
    const val send = "Send"
    const val message = "Message"
    const val replyInThread = "Reply in thread"
    const val replyToThread = "Reply to this thread"
    const val linkPreview = "Link preview"
    const val linkPreviewImage = "Link preview image"
    const val imagePreview = "Image preview"
    const val copyUrl = "Copy URL"
    const val download = "Download"
    const val addReaction = "Add reaction"
    const val noNotifications = "No notifications"
    const val noNotificationsBody = "Mentions and thread replies will show up here."
    const val noWorkspaces = "No workspaces yet"
    const val noWorkspacesBody = "Create the first one to get started."
    const val joinSubtitle = "Choose an existing workspace"
    const val createWorkspaceSubtitle = "A #general channel is created automatically."
    const val workspaceSlugField = "Workspace slug"
    const val workspaceNameField = "Workspace name"
    const val ownerUserIdField = "Owner user id"
    const val ownerDisplayNameField = "Owner display name"
    const val select = "Select"
    const val selectMemberSubtitle = "Continue as an existing member"
    const val noMembers = "No members yet"
    const val noMembersBody = "Create the first member profile on the right."
    const val createMemberSubtitle = "Pick the identity you will use in this workspace."
    const val userIdField = "User id"
    const val displayNameField = "Display name"
    const val generalNoTopic = "No topic"
}

internal object AppStatus {
    const val socketError = "Socket error"
    const val profileUpdated = "Profile updated"
    const val signInPrompt = "Sign in with an existing member or create a new profile."
    const val workspaceOpened = "Workspace opened"
    const val failedLoadOlderMessages = "Failed to load older messages"
    const val failedLoadWorkspaces = "Failed to load workspaces"
    const val failedRefreshNotifications = "Failed to refresh notifications"
    const val notificationStreamDisconnected = "Notification stream disconnected"
    const val failedLoadNotifications = "Failed to load notifications"
    const val creatingWorkspace = "Creating workspace..."
    const val workspaceCreated = "Workspace created with #general"
    const val workspaceCreateFailed = "Workspace creation failed"
    const val creatingMemberProfile = "Creating member profile..."
    const val joinFailed = "Join failed"
    const val creatingChannel = "Creating channel..."
    const val channelCreateFailed = "Channel creation failed"
    const val reactionFailed = "Reaction failed"
    const val messageSent = "Message sent"
    const val sendFailed = "Send failed"
    const val replySent = "Reply sent"
    const val replyFailed = "Reply failed"
    const val profileUpdateFailed = "Profile update failed"
    const val failedLoadThread = "Failed to load thread"
    const val threadLoaded = "Thread loaded"
    const val failedUpdateNotifications = "Failed to update notifications"
    const val channelConnectionFailed = "Channel connection failed"

    fun connectingChannel(slug: String) = "Connecting #$slug..."
    fun channelConnected(slug: String) = "#$slug connected"
    fun signedInAs(name: String) = "Signed in as $name"
    fun joinedAs(name: String) = "Joined as $name"
    fun joinWorkspaceTitle(workspaceName: String?) = "Join ${workspaceName ?: AppLabels.workspace.lowercase()}"
    fun notificationTitleThread(authorDisplayName: String) = "$authorDisplayName replied in a thread"
}
