version: "3.8"
services:
   db:
     image: mysql:8.0
     platform: linux/x86_64
     container_name: mysql-bbs
     environment:
       MYSQL_DATABASE: "bbs"
       MYSQL_ROOT_PASSWORD: "password"
       TZ: "UTC"
     ports:
       - "3131:3306"
